name: Jobs and artifacts

on:
  workflow_dispatch:

jobs:
  generate-artifact:
    runs-on: windows-latest
    steps:
      - name: Build
        run: |
          mkdir -p artifacts
          echo 'ExampleValue' > artifacts/artifact.txt
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-data
          path: artifacts/*.txt

  # You can only download artifacts in a workflow that were uploaded during the same workflow run.
  consume-artifact:
    runs-on: windows-latest
    needs: generate-artifact              # Defines dependency on the generate-artifact job
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: output-data
          path: ./downloaded
      - name: Display structure of downloaded files
        run: |
          Get-ChildItem ./downloaded
      - name: Consume
        run: |
          type downloaded/artifact.txt

  parallel-job:
    runs-on: ubuntu-latest
    needs: generate-artifact
    steps:
      - run: echo 'running other job'


  finishing-job:
    runs-on: windows-latest
    needs:  [consume-artifact, parallel-job]
    steps:
      - run: echo 'running finishing job'