name: Jobs and artifacts

on:
  workflow_dispatch:

jobs:
  generate-artifact:
    runs-on: windows-latest
    steps:
      - name: Build
        run: |
          mkdir -p artifacts
          echo 'ExampleValue' > artifacts/artifact.txt
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-data
          path: artifacts/*.txt

  # You can only download artifacts in a workflow that were uploaded during the same workflow run.
  consume-artifact:
    runs-on: windows-latest
    needs: generate-artifact              # Defines dependency on the generate-artifact job
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: output-data
      - name: Display structure of downloaded files
        run: |
          Get-ChildItem .

      - name: Consume
        run: |
          type artifacts/artifact.txt

