name: Dotnet packages
# See https://docs.github.com/en/actions/guides/building-and-testing-net

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]
    env:
      PROJECTDIR: 'examplelib'

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore $env:PROJECTDIR
      - name: Build
        run: dotnet build --configuration Release --no-restore $env:PROJECTDIR
      - name: Package
        run: dotnet pack -p:PackageVersion=2.1.0 $env:PROJECTDIR