name: Parameters and environment
# see also https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

on:
  workflow_dispatch:
    # These will be visible at the UI when invoking the run workflow dialog
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        default: ['tagA', 'tagB' ]

# see https://docs.github.com/en/actions/reference/environment-variables
env:
  BUILD-ID: ${{ env.GITHUB_RUN_NUMBER }}

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Consume input parameters
        run: |
          echo 'Tags provided: $tags'
          echo 'Log level selected: $logLevel'
      - name: Consume Environment variable
        run: |
          echo 'Tags provided: $tags'
          echo 'Log level selected: $logLevel'
