name: Parameters and environment
# see also https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

on:
  workflow_dispatch:
    # These will be visible at the UI when invoking the run workflow dialog
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'       # value can only be a string, because they translate to env. variables

# see https://docs.github.com/en/actions/reference/environment-variables
env:
 BUILD-TAG: 'TAGA'

jobs:
  variables-usage:
    runs-on: ${{ matrix.os }}
    strategy:    # multiple options to combine
      matrix:
        os: [ubuntu-latest, self-hosted]

    env:                          # variable on the job level
      JOB_LOG_LEVEL: ${{ github.event.inputs.logLevel }}
    steps:
      - name: Consume input parameters
        run: |
          echo "Log level selected: ${{ github.event.inputs.logLevel }}"
      - name: Consume Environment variable
        run: |
          echo "Log level selected: $env:JOB_LOG_LEVEL"
      - name: Use default env. variable
        run: |    # environment variable usage for powershell, in bash $GITHUB_RUN_NUMBER
          echo "Default variable GITHUB_RUN_NUMBER: $env:GITHUB_RUN_NUMBER"
          echo "or another format: ${env:GITHUB_RUN_NUMBER}"
